
export  const DATABASE_CONNECTION = "DATABASE_CONNECTION";

// repositorios
export const PRODUCT_REPOSITORY = "PRODUCT_REPOSITORY";
export const CATEGORY_REPOSITORY = "CATEGORY_REPOSITORY";
export const DEPARTMENT_REPOSITORY = "DEPARTMENT_REPOSITORY";